<h2>Edit message</h2>

<form action=""  method="post">
	<input type="hidden" name="id" value="<?=$data['message']['id'] ?>">
	<div class="form-group">
		<label for="alias">Edit name : </label>
		<input type="text" class="form-control" id="alias" name="name" value="<?=$data['message']['name'] ?>">
	</div>
	<div class="form-group">
		<label for="title"> Edit email : </label>
		<input type="text" class="form-control" id="title" name="email" value="<?=$data['message']['email'] ?>">
	</div>
	<div class="form-group">
		<label for="content">Edit message : </label>
		<textarea class="form-control" id="content" name="message"><?=$data['message']['message'] ?></textarea>
	</div>



	<input type="submit" class="btn btn-default" value="Edit">
</form>
<?php
echo '<pre>';
var_dump($data['message']);