
<h3>Feedback</h3>

<form action="index" method="post">
    <div class="form-group">
        <label for="name">Your name</label>
        <input type="text" class="form-control" id="name" placeholder="Your name" name="name" required>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email" required>
    </div>
    <div class="form-group">
        <label for="message">Your message</label>
        <textarea name="message" id="message" class="form-control" placeholder="Your message" required></textarea>
    </div>

    <input type="submit" class="btn btn-default" value="Send">
</form>