<h3>Edit User</h3>


<form action=""  method="post">
<input type="hidden" name="id" value="<?=$data['user']['id'] ?>">
<div class="form-group">
	<label for="alias">Edit login : </label>
	<input type="text" class="form-control" id="alias" name="login" value="<?=$data['user']['login'] ?>">
</div>
<div class="form-group">
	<label for="title"> Edit email : </label>
	<input type="text" class="form-control" id="title" name="email" value="<?=$data['user']['email'] ?>">
</div>
<div class="form-group">
	<label for="title"> Edit role : </label>
	<input type="text" class="form-control" id="title" name="role" value="<?=$data['user']['role'] ?>">
</div>
<div class="form-group">
	<label for="title"> Edit password : </label>
	<input type="text" class="form-control" id="title" name="password" value="<?=$data['user']['password'] ?>">
</div>
<div class="form-group">
	<label for="is_published"> Active ? </label>
	<input type="checkbox" class="" id="is_published" name="is_active" <?php if ($data['user']['is_active']){?> checked="checked" <?php } ?>
		<?php if($data['user']['is_active']) { ?> value="1" <?php }else { ?> value="0" <?php } ?>>
</div>


<input type="submit" class="btn btn-default" value="Edit">
</form>