<h3>Edit page</h3>

<form action=""  method="post">
    <input type="hidden" name="id" value="<?=$data['pages']['id'] ?>">
    <div class="form-group">
        <label for="alias">Edit alias</label>
        <input type="text" class="form-control" id="alias" name="alias" value="<?=$data['pages']['alias'] ?>">
    </div>
    <div class="form-group">
        <label for="title"> Edit title : </label>
        <input type="text" class="form-control" id="title" name="title" value="<?=$data['pages']['title'] ?>">
    </div>
    <div class="form-group">
        <label for="content">Edit content</label>
        <textarea class="form-control" id="content" name="content"><?=$data['pages']['content'] ?></textarea>
    </div>
    <div class="form-group">
        <label for="is_published"> Publish ? </label>
        <input type="checkbox" class="" id="is_published" name="is_published" <?php if ($data['pages']['is_published']){?> checked="checked" <?php } ?>
        <?php if($data['pages']['is_published']) { ?> value="1" <?php }else { ?> value="0" <?php } ?>>
    </div>


    <input type="submit" class="btn btn-default" value="Edit">
</form>
