<h2>Add page</h2>

<form action=""  method="post">
	<div class="form-group">
		<label for="alias">Add alias</label>
		<input type="text" class="form-control" id="alias" name="alias">
	</div>
	<div class="form-group">
		<label for="title"> Add title : </label>
		<input type="text" class="form-control" id="title" name="title">
	</div>
	<div class="form-group">
		<label for="content">Add content</label>
		<textarea class="form-control" id="content" name="content"></textarea>
	</div>
	<div class="form-group">
		<label for="is_published"> Publish ? </label>
		<input type="checkbox" class="" id="is_published" name="is_published" checked>
	</div>

	<input type="submit" class="btn btn-default" value="Add">
</form>